import { Component, OnInit } from '@angular/core';
import { NgSelectOption } from '@angular/forms';

@Component({
  selector: 'app-input-button-unit',
  template: `
    <p>
    input-button-unit works!
    The title is: {{ title }}
    </p>
    <input [value]="generateTitle()">
    {{ generateTitle() }}
    <button>Save</button>
  `,
  styleUrls: ['./input-button-unit.component.scss']
})
export class InputButtonUnitComponent implements OnInit {
  title = 'Hello, World';

  constructor() {
    this.changeTitle('My first Angular App');
  }

  ngOnInit(): void {
      setTimeout(() => {
      this.title = "This is not the title that you were looking for!";
      }, 3000);
  }

  changeTitle(newTitle: string) {
    this.title = newTitle;
  }

  generateTitle(): string {
    return 'This title was generated by a method.';
  }
}
